backend:
  name: git-gateway
  branch: main  # or 'master' depending on your repo

media_folder: "media"
public_folder: "/media"

collections:
  - name: "events"
    label: "Events"
    folder: "events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Event Name", name: "name", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Link", name: "link", widget: "string", required: false }
